//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Proekt
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Invoice.
    /// </summary>
    // *** Start programmer edit section *** (Invoice CustomAttributes)

    // *** End programmer edit section *** (Invoice CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    public class Invoice : IIS.Proekt.Document
    {
        
        private IIS.Proekt.InvoiceStatus fStatus = IIS.Proekt.InvoiceStatus.New;
        
        private System.DateTime? fShipmentDateTime;
        
        private double fTotalSum;
        
        private double fTotalWeight;
        
        private string fNote;
        
        private string fCustomerName;
        
        private IIS.Proekt.Employee fEmployee;
        
        private IIS.Proekt.Order fOrder;
        
        private IIS.Proekt.DetailArrayOfInvoiceItem fInvoiceItem;
        
        // *** Start programmer edit section *** (Invoice CustomMembers)

        // *** End programmer edit section *** (Invoice CustomMembers)

        
        /// <summary>
        /// CustomerName.
        /// </summary>
        // *** Start programmer edit section *** (Invoice.CustomerName CustomAttributes)

        // *** End programmer edit section *** (Invoice.CustomerName CustomAttributes)
        [StrLen(255)]
        public virtual string CustomerName
        {
            get
            {
                // *** Start programmer edit section *** (Invoice.CustomerName Get start)

                // *** End programmer edit section *** (Invoice.CustomerName Get start)
                string result = this.fCustomerName;
                // *** Start programmer edit section *** (Invoice.CustomerName Get end)

                // *** End programmer edit section *** (Invoice.CustomerName Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Invoice.CustomerName Set start)

                // *** End programmer edit section *** (Invoice.CustomerName Set start)
                this.fCustomerName = value;
                // *** Start programmer edit section *** (Invoice.CustomerName Set end)

                // *** End programmer edit section *** (Invoice.CustomerName Set end)
            }
        }
        
        /// <summary>
        /// Note.
        /// </summary>
        // *** Start programmer edit section *** (Invoice.Note CustomAttributes)

        // *** End programmer edit section *** (Invoice.Note CustomAttributes)
        [StrLen(255)]
        public virtual string Note
        {
            get
            {
                // *** Start programmer edit section *** (Invoice.Note Get start)

                // *** End programmer edit section *** (Invoice.Note Get start)
                string result = this.fNote;
                // *** Start programmer edit section *** (Invoice.Note Get end)

                // *** End programmer edit section *** (Invoice.Note Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Invoice.Note Set start)

                // *** End programmer edit section *** (Invoice.Note Set start)
                this.fNote = value;
                // *** Start programmer edit section *** (Invoice.Note Set end)

                // *** End programmer edit section *** (Invoice.Note Set end)
            }
        }
        
        /// <summary>
        /// ShipmentDateTime.
        /// </summary>
        // *** Start programmer edit section *** (Invoice.ShipmentDateTime CustomAttributes)

        // *** End programmer edit section *** (Invoice.ShipmentDateTime CustomAttributes)
        public virtual System.DateTime? ShipmentDateTime
        {
            get
            {
                // *** Start programmer edit section *** (Invoice.ShipmentDateTime Get start)

                // *** End programmer edit section *** (Invoice.ShipmentDateTime Get start)
                System.DateTime? result = this.fShipmentDateTime;
                // *** Start programmer edit section *** (Invoice.ShipmentDateTime Get end)

                // *** End programmer edit section *** (Invoice.ShipmentDateTime Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Invoice.ShipmentDateTime Set start)

                // *** End programmer edit section *** (Invoice.ShipmentDateTime Set start)
                this.fShipmentDateTime = value;
                // *** Start programmer edit section *** (Invoice.ShipmentDateTime Set end)

                // *** End programmer edit section *** (Invoice.ShipmentDateTime Set end)
            }
        }
        
        /// <summary>
        /// Status.
        /// </summary>
        // *** Start programmer edit section *** (Invoice.Status CustomAttributes)

        // *** End programmer edit section *** (Invoice.Status CustomAttributes)
        public virtual IIS.Proekt.InvoiceStatus Status
        {
            get
            {
                // *** Start programmer edit section *** (Invoice.Status Get start)

                // *** End programmer edit section *** (Invoice.Status Get start)
                IIS.Proekt.InvoiceStatus result = this.fStatus;
                // *** Start programmer edit section *** (Invoice.Status Get end)

                // *** End programmer edit section *** (Invoice.Status Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Invoice.Status Set start)

                // *** End programmer edit section *** (Invoice.Status Set start)
                this.fStatus = value;
                // *** Start programmer edit section *** (Invoice.Status Set end)

                // *** End programmer edit section *** (Invoice.Status Set end)
            }
        }
        
        /// <summary>
        /// TotalSum.
        /// </summary>
        // *** Start programmer edit section *** (Invoice.TotalSum CustomAttributes)

        // *** End programmer edit section *** (Invoice.TotalSum CustomAttributes)
        public virtual double TotalSum
        {
            get
            {
                // *** Start programmer edit section *** (Invoice.TotalSum Get start)

                // *** End programmer edit section *** (Invoice.TotalSum Get start)
                double result = this.fTotalSum;
                // *** Start programmer edit section *** (Invoice.TotalSum Get end)

                // *** End programmer edit section *** (Invoice.TotalSum Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Invoice.TotalSum Set start)

                // *** End programmer edit section *** (Invoice.TotalSum Set start)
                this.fTotalSum = value;
                // *** Start programmer edit section *** (Invoice.TotalSum Set end)

                // *** End programmer edit section *** (Invoice.TotalSum Set end)
            }
        }
        
        /// <summary>
        /// TotalWeight.
        /// </summary>
        // *** Start programmer edit section *** (Invoice.TotalWeight CustomAttributes)

        // *** End programmer edit section *** (Invoice.TotalWeight CustomAttributes)
        public virtual double TotalWeight
        {
            get
            {
                // *** Start programmer edit section *** (Invoice.TotalWeight Get start)

                // *** End programmer edit section *** (Invoice.TotalWeight Get start)
                double result = this.fTotalWeight;
                // *** Start programmer edit section *** (Invoice.TotalWeight Get end)

                // *** End programmer edit section *** (Invoice.TotalWeight Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Invoice.TotalWeight Set start)

                // *** End programmer edit section *** (Invoice.TotalWeight Set start)
                this.fTotalWeight = value;
                // *** Start programmer edit section *** (Invoice.TotalWeight Set end)

                // *** End programmer edit section *** (Invoice.TotalWeight Set end)
            }
        }
        
        /// <summary>
        /// Invoice.
        /// </summary>
        // *** Start programmer edit section *** (Invoice.Employee CustomAttributes)

        // *** End programmer edit section *** (Invoice.Employee CustomAttributes)
        public virtual IIS.Proekt.Employee Employee
        {
            get
            {
                // *** Start programmer edit section *** (Invoice.Employee Get start)

                // *** End programmer edit section *** (Invoice.Employee Get start)
                IIS.Proekt.Employee result = this.fEmployee;
                // *** Start programmer edit section *** (Invoice.Employee Get end)

                // *** End programmer edit section *** (Invoice.Employee Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Invoice.Employee Set start)

                // *** End programmer edit section *** (Invoice.Employee Set start)
                this.fEmployee = value;
                // *** Start programmer edit section *** (Invoice.Employee Set end)

                // *** End programmer edit section *** (Invoice.Employee Set end)
            }
        }
        
        /// <summary>
        /// Invoice.
        /// </summary>
        // *** Start programmer edit section *** (Invoice.Order CustomAttributes)

        // *** End programmer edit section *** (Invoice.Order CustomAttributes)
        public virtual IIS.Proekt.Order Order
        {
            get
            {
                // *** Start programmer edit section *** (Invoice.Order Get start)

                // *** End programmer edit section *** (Invoice.Order Get start)
                IIS.Proekt.Order result = this.fOrder;
                // *** Start programmer edit section *** (Invoice.Order Get end)

                // *** End programmer edit section *** (Invoice.Order Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Invoice.Order Set start)

                // *** End programmer edit section *** (Invoice.Order Set start)
                this.fOrder = value;
                // *** Start programmer edit section *** (Invoice.Order Set end)

                // *** End programmer edit section *** (Invoice.Order Set end)
            }
        }
        
        /// <summary>
        /// Invoice.
        /// </summary>
        // *** Start programmer edit section *** (Invoice.InvoiceItem CustomAttributes)

        // *** End programmer edit section *** (Invoice.InvoiceItem CustomAttributes)
        public virtual IIS.Proekt.DetailArrayOfInvoiceItem InvoiceItem
        {
            get
            {
                // *** Start programmer edit section *** (Invoice.InvoiceItem Get start)

                // *** End programmer edit section *** (Invoice.InvoiceItem Get start)
                if ((this.fInvoiceItem == null))
                {
                    this.fInvoiceItem = new IIS.Proekt.DetailArrayOfInvoiceItem(this);
                }
                IIS.Proekt.DetailArrayOfInvoiceItem result = this.fInvoiceItem;
                // *** Start programmer edit section *** (Invoice.InvoiceItem Get end)

                // *** End programmer edit section *** (Invoice.InvoiceItem Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Invoice.InvoiceItem Set start)

                // *** End programmer edit section *** (Invoice.InvoiceItem Set start)
                this.fInvoiceItem = value;
                // *** Start programmer edit section *** (Invoice.InvoiceItem Set end)

                // *** End programmer edit section *** (Invoice.InvoiceItem Set end)
            }
        }
    }
}
