//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Proekt
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// InvoiceItem.
    /// </summary>
    // *** Start programmer edit section *** (InvoiceItem CustomAttributes)

    // *** End programmer edit section *** (InvoiceItem CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    public class InvoiceItem : ICSSoft.STORMNET.DataObject
    {
        
        private int fAmount;
        
        private double fWeight;
        
        private double fPrice;
        
        private double fTotalSum;
        
        private IIS.Proekt.Product fProduct;
        
        private IIS.Proekt.Invoice fInvoice;
        
        // *** Start programmer edit section *** (InvoiceItem CustomMembers)

        // *** End programmer edit section *** (InvoiceItem CustomMembers)

        
        /// <summary>
        /// Amount.
        /// </summary>
        // *** Start programmer edit section *** (InvoiceItem.Amount CustomAttributes)

        // *** End programmer edit section *** (InvoiceItem.Amount CustomAttributes)
        public virtual int Amount
        {
            get
            {
                // *** Start programmer edit section *** (InvoiceItem.Amount Get start)

                // *** End programmer edit section *** (InvoiceItem.Amount Get start)
                int result = this.fAmount;
                // *** Start programmer edit section *** (InvoiceItem.Amount Get end)

                // *** End programmer edit section *** (InvoiceItem.Amount Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (InvoiceItem.Amount Set start)

                // *** End programmer edit section *** (InvoiceItem.Amount Set start)
                this.fAmount = value;
                // *** Start programmer edit section *** (InvoiceItem.Amount Set end)

                // *** End programmer edit section *** (InvoiceItem.Amount Set end)
            }
        }
        
        /// <summary>
        /// Price.
        /// </summary>
        // *** Start programmer edit section *** (InvoiceItem.Price CustomAttributes)

        // *** End programmer edit section *** (InvoiceItem.Price CustomAttributes)
        public virtual double Price
        {
            get
            {
                // *** Start programmer edit section *** (InvoiceItem.Price Get start)

                // *** End programmer edit section *** (InvoiceItem.Price Get start)
                double result = this.fPrice;
                // *** Start programmer edit section *** (InvoiceItem.Price Get end)

                // *** End programmer edit section *** (InvoiceItem.Price Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (InvoiceItem.Price Set start)

                // *** End programmer edit section *** (InvoiceItem.Price Set start)
                this.fPrice = value;
                // *** Start programmer edit section *** (InvoiceItem.Price Set end)

                // *** End programmer edit section *** (InvoiceItem.Price Set end)
            }
        }
        
        /// <summary>
        /// TotalSum.
        /// </summary>
        // *** Start programmer edit section *** (InvoiceItem.TotalSum CustomAttributes)

        // *** End programmer edit section *** (InvoiceItem.TotalSum CustomAttributes)
        public virtual double TotalSum
        {
            get
            {
                // *** Start programmer edit section *** (InvoiceItem.TotalSum Get start)

                // *** End programmer edit section *** (InvoiceItem.TotalSum Get start)
                double result = this.fTotalSum;
                // *** Start programmer edit section *** (InvoiceItem.TotalSum Get end)

                // *** End programmer edit section *** (InvoiceItem.TotalSum Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (InvoiceItem.TotalSum Set start)

                // *** End programmer edit section *** (InvoiceItem.TotalSum Set start)
                this.fTotalSum = value;
                // *** Start programmer edit section *** (InvoiceItem.TotalSum Set end)

                // *** End programmer edit section *** (InvoiceItem.TotalSum Set end)
            }
        }
        
        /// <summary>
        /// Weight.
        /// </summary>
        // *** Start programmer edit section *** (InvoiceItem.Weight CustomAttributes)

        // *** End programmer edit section *** (InvoiceItem.Weight CustomAttributes)
        public virtual double Weight
        {
            get
            {
                // *** Start programmer edit section *** (InvoiceItem.Weight Get start)

                // *** End programmer edit section *** (InvoiceItem.Weight Get start)
                double result = this.fWeight;
                // *** Start programmer edit section *** (InvoiceItem.Weight Get end)

                // *** End programmer edit section *** (InvoiceItem.Weight Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (InvoiceItem.Weight Set start)

                // *** End programmer edit section *** (InvoiceItem.Weight Set start)
                this.fWeight = value;
                // *** Start programmer edit section *** (InvoiceItem.Weight Set end)

                // *** End programmer edit section *** (InvoiceItem.Weight Set end)
            }
        }
        
        /// <summary>
        /// InvoiceItem.
        /// </summary>
        // *** Start programmer edit section *** (InvoiceItem.Product CustomAttributes)

        // *** End programmer edit section *** (InvoiceItem.Product CustomAttributes)
        public virtual IIS.Proekt.Product Product
        {
            get
            {
                // *** Start programmer edit section *** (InvoiceItem.Product Get start)

                // *** End programmer edit section *** (InvoiceItem.Product Get start)
                IIS.Proekt.Product result = this.fProduct;
                // *** Start programmer edit section *** (InvoiceItem.Product Get end)

                // *** End programmer edit section *** (InvoiceItem.Product Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (InvoiceItem.Product Set start)

                // *** End programmer edit section *** (InvoiceItem.Product Set start)
                this.fProduct = value;
                // *** Start programmer edit section *** (InvoiceItem.Product Set end)

                // *** End programmer edit section *** (InvoiceItem.Product Set end)
            }
        }
        
        /// <summary>
        /// мастеровая ссылка на шапку IIS.Proekt.Invoice.
        /// </summary>
        // *** Start programmer edit section *** (InvoiceItem.Invoice CustomAttributes)

        // *** End programmer edit section *** (InvoiceItem.Invoice CustomAttributes)
        [Agregator()]
        [NotNull()]
        public virtual IIS.Proekt.Invoice Invoice
        {
            get
            {
                // *** Start programmer edit section *** (InvoiceItem.Invoice Get start)

                // *** End programmer edit section *** (InvoiceItem.Invoice Get start)
                IIS.Proekt.Invoice result = this.fInvoice;
                // *** Start programmer edit section *** (InvoiceItem.Invoice Get end)

                // *** End programmer edit section *** (InvoiceItem.Invoice Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (InvoiceItem.Invoice Set start)

                // *** End programmer edit section *** (InvoiceItem.Invoice Set start)
                this.fInvoice = value;
                // *** Start programmer edit section *** (InvoiceItem.Invoice Set end)

                // *** End programmer edit section *** (InvoiceItem.Invoice Set end)
            }
        }
    }
    
    /// <summary>
    /// Detail array of InvoiceItem.
    /// </summary>
    // *** Start programmer edit section *** (DetailArrayDetailArrayOfInvoiceItem CustomAttributes)

    // *** End programmer edit section *** (DetailArrayDetailArrayOfInvoiceItem CustomAttributes)
    public class DetailArrayOfInvoiceItem : ICSSoft.STORMNET.DetailArray
    {
        
        // *** Start programmer edit section *** (IIS.Proekt.DetailArrayOfInvoiceItem members)

        // *** End programmer edit section *** (IIS.Proekt.DetailArrayOfInvoiceItem members)

        
        /// <summary>
        /// Construct detail array.
        /// </summary>
        /// <summary>
        /// Returns object with type InvoiceItem by index.
        /// </summary>
        /// <summary>
        /// Adds object with type InvoiceItem.
        /// </summary>
        public DetailArrayOfInvoiceItem(IIS.Proekt.Invoice fInvoice) : 
                base(typeof(InvoiceItem), ((ICSSoft.STORMNET.DataObject)(fInvoice)))
        {
        }
        
        public IIS.Proekt.InvoiceItem this[int index]
        {
            get
            {
                return ((IIS.Proekt.InvoiceItem)(this.ItemByIndex(index)));
            }
        }
        
        public virtual void Add(IIS.Proekt.InvoiceItem dataobject)
        {
            this.AddObject(((ICSSoft.STORMNET.DataObject)(dataobject)));
        }
    }
}
