//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Proekt
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Product.
    /// </summary>
    // *** Start programmer edit section *** (Product CustomAttributes)

    // *** End programmer edit section *** (Product CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    public class Product : ICSSoft.STORMNET.DataObject
    {
        
        private int fProductCode = 1;
        
        private string fName;
        
        private string fMeasure;
        
        private string fDescription;
        
        private double fPrice;
        
        private double fWeight;
        
        // *** Start programmer edit section *** (Product CustomMembers)

        // *** End programmer edit section *** (Product CustomMembers)

        
        /// <summary>
        /// Description.
        /// </summary>
        // *** Start programmer edit section *** (Product.Description CustomAttributes)

        // *** End programmer edit section *** (Product.Description CustomAttributes)
        [StrLen(255)]
        public virtual string Description
        {
            get
            {
                // *** Start programmer edit section *** (Product.Description Get start)

                // *** End programmer edit section *** (Product.Description Get start)
                string result = this.fDescription;
                // *** Start programmer edit section *** (Product.Description Get end)

                // *** End programmer edit section *** (Product.Description Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Product.Description Set start)

                // *** End programmer edit section *** (Product.Description Set start)
                this.fDescription = value;
                // *** Start programmer edit section *** (Product.Description Set end)

                // *** End programmer edit section *** (Product.Description Set end)
            }
        }
        
        /// <summary>
        /// Measure.
        /// </summary>
        // *** Start programmer edit section *** (Product.Measure CustomAttributes)

        // *** End programmer edit section *** (Product.Measure CustomAttributes)
        [StrLen(255)]
        public virtual string Measure
        {
            get
            {
                // *** Start programmer edit section *** (Product.Measure Get start)

                // *** End programmer edit section *** (Product.Measure Get start)
                string result = this.fMeasure;
                // *** Start programmer edit section *** (Product.Measure Get end)

                // *** End programmer edit section *** (Product.Measure Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Product.Measure Set start)

                // *** End programmer edit section *** (Product.Measure Set start)
                this.fMeasure = value;
                // *** Start programmer edit section *** (Product.Measure Set end)

                // *** End programmer edit section *** (Product.Measure Set end)
            }
        }
        
        /// <summary>
        /// Name.
        /// </summary>
        // *** Start programmer edit section *** (Product.Name CustomAttributes)

        // *** End programmer edit section *** (Product.Name CustomAttributes)
        [StrLen(255)]
        public virtual string Name
        {
            get
            {
                // *** Start programmer edit section *** (Product.Name Get start)

                // *** End programmer edit section *** (Product.Name Get start)
                string result = this.fName;
                // *** Start programmer edit section *** (Product.Name Get end)

                // *** End programmer edit section *** (Product.Name Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Product.Name Set start)

                // *** End programmer edit section *** (Product.Name Set start)
                this.fName = value;
                // *** Start programmer edit section *** (Product.Name Set end)

                // *** End programmer edit section *** (Product.Name Set end)
            }
        }
        
        /// <summary>
        /// Price.
        /// </summary>
        // *** Start programmer edit section *** (Product.Price CustomAttributes)

        // *** End programmer edit section *** (Product.Price CustomAttributes)
        public virtual double Price
        {
            get
            {
                // *** Start programmer edit section *** (Product.Price Get start)

                // *** End programmer edit section *** (Product.Price Get start)
                double result = this.fPrice;
                // *** Start programmer edit section *** (Product.Price Get end)

                // *** End programmer edit section *** (Product.Price Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Product.Price Set start)

                // *** End programmer edit section *** (Product.Price Set start)
                this.fPrice = value;
                // *** Start programmer edit section *** (Product.Price Set end)

                // *** End programmer edit section *** (Product.Price Set end)
            }
        }
        
        /// <summary>
        /// ProductCode.
        /// </summary>
        // *** Start programmer edit section *** (Product.ProductCode CustomAttributes)

        // *** End programmer edit section *** (Product.ProductCode CustomAttributes)
        [NotNull()]
        public virtual int ProductCode
        {
            get
            {
                // *** Start programmer edit section *** (Product.ProductCode Get start)

                // *** End programmer edit section *** (Product.ProductCode Get start)
                int result = this.fProductCode;
                // *** Start programmer edit section *** (Product.ProductCode Get end)

                // *** End programmer edit section *** (Product.ProductCode Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Product.ProductCode Set start)

                // *** End programmer edit section *** (Product.ProductCode Set start)
                this.fProductCode = value;
                // *** Start programmer edit section *** (Product.ProductCode Set end)

                // *** End programmer edit section *** (Product.ProductCode Set end)
            }
        }
        
        /// <summary>
        /// Weight.
        /// </summary>
        // *** Start programmer edit section *** (Product.Weight CustomAttributes)

        // *** End programmer edit section *** (Product.Weight CustomAttributes)
        public virtual double Weight
        {
            get
            {
                // *** Start programmer edit section *** (Product.Weight Get start)

                // *** End programmer edit section *** (Product.Weight Get start)
                double result = this.fWeight;
                // *** Start programmer edit section *** (Product.Weight Get end)

                // *** End programmer edit section *** (Product.Weight Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Product.Weight Set start)

                // *** End programmer edit section *** (Product.Weight Set start)
                this.fWeight = value;
                // *** Start programmer edit section *** (Product.Weight Set end)

                // *** End programmer edit section *** (Product.Weight Set end)
            }
        }
    }
}
