//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Proekt
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// StoreProduct.
    /// </summary>
    // *** Start programmer edit section *** (StoreProduct CustomAttributes)

    // *** End programmer edit section *** (StoreProduct CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    public class StoreProduct : ICSSoft.STORMNET.DataObject
    {
        
        private int fAmount;
        
        private IIS.Proekt.Product fProduct;
        
        private IIS.Proekt.Storehouse fStorehouse;
        
        // *** Start programmer edit section *** (StoreProduct CustomMembers)

        // *** End programmer edit section *** (StoreProduct CustomMembers)

        
        /// <summary>
        /// Amount.
        /// </summary>
        // *** Start programmer edit section *** (StoreProduct.Amount CustomAttributes)

        // *** End programmer edit section *** (StoreProduct.Amount CustomAttributes)
        public virtual int Amount
        {
            get
            {
                // *** Start programmer edit section *** (StoreProduct.Amount Get start)

                // *** End programmer edit section *** (StoreProduct.Amount Get start)
                int result = this.fAmount;
                // *** Start programmer edit section *** (StoreProduct.Amount Get end)

                // *** End programmer edit section *** (StoreProduct.Amount Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (StoreProduct.Amount Set start)

                // *** End programmer edit section *** (StoreProduct.Amount Set start)
                this.fAmount = value;
                // *** Start programmer edit section *** (StoreProduct.Amount Set end)

                // *** End programmer edit section *** (StoreProduct.Amount Set end)
            }
        }
        
        /// <summary>
        /// StoreProduct.
        /// </summary>
        // *** Start programmer edit section *** (StoreProduct.Product CustomAttributes)

        // *** End programmer edit section *** (StoreProduct.Product CustomAttributes)
        public virtual IIS.Proekt.Product Product
        {
            get
            {
                // *** Start programmer edit section *** (StoreProduct.Product Get start)

                // *** End programmer edit section *** (StoreProduct.Product Get start)
                IIS.Proekt.Product result = this.fProduct;
                // *** Start programmer edit section *** (StoreProduct.Product Get end)

                // *** End programmer edit section *** (StoreProduct.Product Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (StoreProduct.Product Set start)

                // *** End programmer edit section *** (StoreProduct.Product Set start)
                this.fProduct = value;
                // *** Start programmer edit section *** (StoreProduct.Product Set end)

                // *** End programmer edit section *** (StoreProduct.Product Set end)
            }
        }
        
        /// <summary>
        /// мастеровая ссылка на шапку IIS.Proekt.Storehouse.
        /// </summary>
        // *** Start programmer edit section *** (StoreProduct.Storehouse CustomAttributes)

        // *** End programmer edit section *** (StoreProduct.Storehouse CustomAttributes)
        [Agregator()]
        [NotNull()]
        public virtual IIS.Proekt.Storehouse Storehouse
        {
            get
            {
                // *** Start programmer edit section *** (StoreProduct.Storehouse Get start)

                // *** End programmer edit section *** (StoreProduct.Storehouse Get start)
                IIS.Proekt.Storehouse result = this.fStorehouse;
                // *** Start programmer edit section *** (StoreProduct.Storehouse Get end)

                // *** End programmer edit section *** (StoreProduct.Storehouse Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (StoreProduct.Storehouse Set start)

                // *** End programmer edit section *** (StoreProduct.Storehouse Set start)
                this.fStorehouse = value;
                // *** Start programmer edit section *** (StoreProduct.Storehouse Set end)

                // *** End programmer edit section *** (StoreProduct.Storehouse Set end)
            }
        }
    }
    
    /// <summary>
    /// Detail array of StoreProduct.
    /// </summary>
    // *** Start programmer edit section *** (DetailArrayDetailArrayOfStoreProduct CustomAttributes)

    // *** End programmer edit section *** (DetailArrayDetailArrayOfStoreProduct CustomAttributes)
    public class DetailArrayOfStoreProduct : ICSSoft.STORMNET.DetailArray
    {
        
        // *** Start programmer edit section *** (IIS.Proekt.DetailArrayOfStoreProduct members)

        // *** End programmer edit section *** (IIS.Proekt.DetailArrayOfStoreProduct members)

        
        /// <summary>
        /// Construct detail array.
        /// </summary>
        /// <summary>
        /// Returns object with type StoreProduct by index.
        /// </summary>
        /// <summary>
        /// Adds object with type StoreProduct.
        /// </summary>
        public DetailArrayOfStoreProduct(IIS.Proekt.Storehouse fStorehouse) : 
                base(typeof(StoreProduct), ((ICSSoft.STORMNET.DataObject)(fStorehouse)))
        {
        }
        
        public IIS.Proekt.StoreProduct this[int index]
        {
            get
            {
                return ((IIS.Proekt.StoreProduct)(this.ItemByIndex(index)));
            }
        }
        
        public virtual void Add(IIS.Proekt.StoreProduct dataobject)
        {
            this.AddObject(((ICSSoft.STORMNET.DataObject)(dataobject)));
        }
    }
}
